scrape_configs:
  - job_name: 'HeymartMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:3031']
        labels:
          application: 'heymart-auth'